name: Lint files

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master] # or "develop" / "main" depending on your setup

concurrency:
  group: Lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    name: Lint PHP files (Laravel Pint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@36de00d5f5a8a4e12d443e01671daa12a18f4c79
        with:
          configPath: pint.json
          pintVersion: '1.25.0'

      - name: Check for uncommitted changes
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "ðŸ›‘ Laravel Pint found formatting changes:\n$status"
            echo "::error::Please run 'vendor/bin/pint' locally and commit the fixes."
            exit 1
          fi
